package firebase

import (
	"encoding/json"
	"fmt"
	"os/exec"
	"strings"
)

// SiteExists checks if a Firebase Hosting site exists.
func SiteExists(projectID, siteName string) (bool, error) {
	cmd := exec.Command("firebase", "hosting:sites:list", "--project", projectID, "--json")
	out, err := cmd.Output()
	if err != nil {
		return false, fmt.Errorf("failed to list hosting sites: %w", err)
	}

	var result struct {
		Sites []struct {
			Name string `json:"name"`
		} `json:"sites"`
	}
	if err := json.Unmarshal(out, &result); err != nil {
		// Firebase CLI may wrap output differently; try parsing as status.
		return false, nil
	}

	fullName := fmt.Sprintf("projects/%s/sites/%s", projectID, siteName)
	for _, s := range result.Sites {
		if s.Name == fullName || s.Name == siteName {
			return true, nil
		}
	}
	return false, nil
}

// CreateSite creates a Firebase Hosting site.
func CreateSite(projectID, siteName string) error {
	cmd := exec.Command("firebase", "hosting:sites:create", siteName, "--project", projectID)
	cmd.Stdout = nil
	cmd.Stderr = nil
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to create hosting site %s: %s", siteName, string(out))
	}
	fmt.Printf("✓ Created Firebase Hosting site: %s\n", siteName)
	return nil
}

// DeployPlaceholder deploys a minimal placeholder page.
func DeployPlaceholder(projectID, siteName string) error {
	// Firebase deploy requires a firebase.json and public directory.
	// We'll use the CLI's --only hosting approach with a temp config.
	cmd := exec.Command("firebase", "hosting:channel:deploy", "live",
		"--project", projectID,
		"--site", siteName,
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to deploy placeholder: %s", string(out))
	}
	fmt.Printf("✓ Deployed to %s.web.app\n", siteName)
	return nil
}

// GetAutoURL returns the auto-generated hosting URL.
func GetAutoURL(siteName string) string {
	return fmt.Sprintf("https://%s.web.app", siteName)
}

// AddCustomDomain adds a custom domain to Firebase Hosting.
// Returns required DNS records (TXT for verification, A/AAAA for pointing).
func AddCustomDomain(projectID, siteName, domain string) ([]DNSRecord, error) {
	cmd := exec.Command("firebase", "hosting:custom-domains:create",
		domain,
		"--project", projectID,
		"--site", siteName,
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		output := string(out)
		// Try to extract DNS records from error/output.
		records := parseDNSRecords(output)
		if len(records) > 0 {
			return records, nil
		}
		return nil, fmt.Errorf("failed to add custom domain: %s", output)
	}

	records := parseDNSRecords(string(out))
	return records, nil
}

// DNSRecord represents a DNS record required by Firebase.
type DNSRecord struct {
	Type    string
	Name    string
	Content string
}

// GetRequiredDNSRecords returns the standard Firebase Hosting DNS records for apex domains.
func GetRequiredDNSRecords(domain string) []DNSRecord {
	return []DNSRecord{
		{Type: "A", Name: domain, Content: "199.36.158.100"},
		{Type: "TXT", Name: fmt.Sprintf("_acme-challenge.%s", domain), Content: "(auto-generated by Firebase)"},
	}
}

func parseDNSRecords(output string) []DNSRecord {
	var records []DNSRecord
	lines := strings.Split(output, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		// Look for lines that contain record info (heuristic).
		if strings.Contains(line, "TXT") || strings.Contains(line, " A ") || strings.Contains(line, "AAAA") {
			parts := strings.Fields(line)
			if len(parts) >= 3 {
				records = append(records, DNSRecord{
					Type:    parts[0],
					Name:    parts[1],
					Content: parts[2],
				})
			}
		}
	}
	return records
}
