package firebase

import (
	"context"
	"encoding/json"
	"fmt"
	"os/exec"
	"strings"

	"github.com/trakhimenok/hoston/internal/provider"
)

// Compile-time check that *Provider implements provider.HostingProvider.
var _ provider.HostingProvider = (*Provider)(nil)

// Provider implements provider.HostingProvider for Firebase Hosting.
type Provider struct{}

// NewProvider returns a new Firebase Hosting Provider.
func NewProvider() *Provider {
	return &Provider{}
}

// Name returns the human-readable name of this hosting provider.
func (p *Provider) Name() string {
	return "Firebase Hosting"
}

// Setup creates (or verifies) a Firebase Hosting site for the given domain and
// returns the DNS records that must be configured at the DNS provider.
//
// Required params:
//   - "project_id"  – Firebase project ID
//   - "site_name"   – Firebase Hosting site name (subdomain of web.app)
func (p *Provider) Setup(ctx context.Context, domain string, params map[string]string) ([]provider.DNSRecord, error) {
	projectID := params["project_id"]
	siteName := params["site_name"]

	if projectID == "" {
		return nil, fmt.Errorf("firebase: missing required param \"project_id\"")
	}
	if siteName == "" {
		return nil, fmt.Errorf("firebase: missing required param \"site_name\"")
	}

	exists, err := SiteExists(projectID, siteName)
	if err != nil {
		return nil, fmt.Errorf("firebase: checking site existence: %w", err)
	}

	if !exists {
		if err := CreateSite(projectID, siteName); err != nil {
			return nil, fmt.Errorf("firebase: creating site: %w", err)
		}
	}

	localRecords, err := AddCustomDomain(projectID, siteName, domain)
	if err != nil {
		return nil, fmt.Errorf("firebase: adding custom domain: %w", err)
	}

	// Fall back to well-known static records when the CLI returns none.
	if len(localRecords) == 0 {
		localRecords = GetRequiredDNSRecords(domain)
	}

	return localRecords, nil
}

// SiteExists checks if a Firebase Hosting site exists.
func SiteExists(projectID, siteName string) (bool, error) {
	cmd := exec.Command("firebase", "hosting:sites:list", "--project", projectID, "--json")
	out, err := cmd.Output()
	if err != nil {
		return false, fmt.Errorf("failed to list hosting sites: %w", err)
	}

	var result struct {
		Sites []struct {
			Name string `json:"name"`
		} `json:"sites"`
	}
	if err := json.Unmarshal(out, &result); err != nil {
		return false, fmt.Errorf("failed to parse sites response: %w", err)
	}

	fullName := fmt.Sprintf("projects/%s/sites/%s", projectID, siteName)
	for _, s := range result.Sites {
		if s.Name == fullName || s.Name == siteName {
			return true, nil
		}
	}
	return false, nil
}

// CreateSite creates a Firebase Hosting site.
func CreateSite(projectID, siteName string) error {
	cmd := exec.Command("firebase", "hosting:sites:create", siteName, "--project", projectID)
	cmd.Stdout = nil
	cmd.Stderr = nil
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to create hosting site %s: %s", siteName, string(out))
	}
	fmt.Printf("✓ Created Firebase Hosting site: %s\n", siteName)
	return nil
}

// DeployPlaceholder deploys a minimal placeholder page.
func DeployPlaceholder(projectID, siteName string) error {
	// Firebase deploy requires a firebase.json and public directory.
	// We'll use the CLI's --only hosting approach with a temp config.
	cmd := exec.Command("firebase", "hosting:channel:deploy", "live",
		"--project", projectID,
		"--site", siteName,
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to deploy placeholder: %s", string(out))
	}
	fmt.Printf("✓ Deployed to %s.web.app\n", siteName)
	return nil
}

// GetAutoURL returns the auto-generated hosting URL.
func GetAutoURL(siteName string) string {
	return fmt.Sprintf("https://%s.web.app", siteName)
}

// AddCustomDomain adds a custom domain to Firebase Hosting.
// Returns required DNS records (TXT for verification, A/AAAA for pointing).
func AddCustomDomain(projectID, siteName, domain string) ([]provider.DNSRecord, error) {
	cmd := exec.Command("firebase", "hosting:custom-domains:create",
		domain,
		"--project", projectID,
		"--site", siteName,
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		output := string(out)
		// Try to extract DNS records from error/output.
		records := parseDNSRecords(output)
		if len(records) > 0 {
			return records, nil
		}
		return nil, fmt.Errorf("failed to add custom domain: %s", output)
	}

	records := parseDNSRecords(string(out))
	return records, nil
}

// GetRequiredDNSRecords returns the standard Firebase Hosting DNS records for apex domains.
func GetRequiredDNSRecords(domain string) []provider.DNSRecord {
	return []provider.DNSRecord{
		{Type: "A", Name: domain, Content: "199.36.158.100"},
		{Type: "TXT", Name: fmt.Sprintf("_acme-challenge.%s", domain), Content: "(auto-generated by Firebase)"},
	}
}

func parseDNSRecords(output string) []provider.DNSRecord {
	var records []provider.DNSRecord
	lines := strings.Split(output, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		// Look for lines that contain record info (heuristic).
		if strings.Contains(line, "TXT") || strings.Contains(line, " A ") || strings.Contains(line, "AAAA") {
			parts := strings.Fields(line)
			if len(parts) >= 3 {
				records = append(records, provider.DNSRecord{
					Type:    parts[0],
					Name:    parts[1],
					Content: parts[2],
				})
			}
		}
	}
	return records
}
